version: '3'
services:

  grpc-server:
    image: vatsan127/grpc_server
    ports:
      - "8080:8080"
      - "6565:6565"

  grpc-client:
    image: vatsan127/grpc_client
    ports:
      - "8082:8080"
    environment:
      - GRPC_SERVER_HOST=grpc-server
      - GRPC_SERVER_PORT=6565

    depends_on:
      - grpc-server
